task_name: run_requests
seed: 7777
n_threads: 4
use_gpu: True
defaults:
  - _self_
  - model: base_vlm
  - task: base_task
  - paths: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .